//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assigment1._2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRental : DbContext
    {
        public CarRental()
            : base("name=CarRental")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarRentalCompany> CarRentalCompanies { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<TravelAgency> TravelAgencies { get; set; }

        public System.Data.Entity.DbSet<FIT5032_Assigment1._2.Models.Location> Locations { get; set; }
    }
}
