using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assigment1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int AgencyId { get; set; }
        public string CustomerId { get; set; }
        public string CarType { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime PickupDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ReturnDate { get; set; }
        public string PickupLocation { get; set; }
        public string ReturnLocation { get; set; }
    
        public virtual TravelAgency TravelAgency { get; set; }
    }
}
