-- ----------------------------
-- Table structure for BRANCHES
-- ----------------------------
DROP TABLE "DEVUSER"."BRANCHES";
CREATE TABLE "DEVUSER"."BRANCHES" (
  "BRANCH_NUM" NUMBER VISIBLE NOT NULL,
  "branch_name" VARCHAR2(255 BYTE) VISIBLE,
  "address" VARCHAR2(255 BYTE) VISIBLE
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CHECKING_ACCOUNTS
-- ----------------------------
DROP TABLE "DEVUSER"."CHECKING_ACCOUNTS";
CREATE TABLE "DEVUSER"."CHECKING_ACCOUNTS" (
  "ACCOUNT_NUM" NUMBER VISIBLE NOT NULL,
  "branch_num" NUMBER VISIBLE,
  "date_opened" DATE VISIBLE,
  "balance" NUMBER(38,2) VISIBLE,
  "overdraft_amount" NUMBER(38,2) VISIBLE,
  "check_limit" NUMBER(38,2) VISIBLE
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CUSTOMERS
-- ----------------------------
DROP TABLE "DEVUSER"."CUSTOMERS";
CREATE TABLE "DEVUSER"."CUSTOMERS" (
  "CUSTOMER_NUM" NUMBER VISIBLE NOT NULL,
  "name" VARCHAR2(255 BYTE) VISIBLE,
  "address" VARCHAR2(255 BYTE) VISIBLE,
  "phone" VARCHAR2(255 BYTE) VISIBLE
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for HAS_ACCOUNT
-- ----------------------------
DROP TABLE "DEVUSER"."HAS_ACCOUNT";
CREATE TABLE "DEVUSER"."HAS_ACCOUNT" (
  "CUSTOMER_NUM" NUMBER VISIBLE NOT NULL,
  "ACCOUNT_TYPE" NUMBER VISIBLE NOT NULL,
  "ACCOUNT_NUM" NUMBER VISIBLE NOT NULL
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for LOAN_ACCOUNTS
-- ----------------------------
DROP TABLE "DEVUSER"."LOAN_ACCOUNTS";
CREATE TABLE "DEVUSER"."LOAN_ACCOUNTS" (
  "ACCOUNT_NUM" NUMBER VISIBLE NOT NULL,
  "branch_num" NUMBER VISIBLE,
  "date_opened" DATE VISIBLE,
  "loan_type" NUMBER VISIBLE,
  "interest_rate" NUMBER(38,2) VISIBLE
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SAVINGS_ACCOUNTS
-- ----------------------------
DROP TABLE "DEVUSER"."SAVINGS_ACCOUNTS";
CREATE TABLE "DEVUSER"."SAVINGS_ACCOUNTS" (
  "ACCOUNT_NUM" NUMBER VISIBLE NOT NULL,
  "branch_num" NUMBER VISIBLE,
  "date_opened" DATE VISIBLE,
  "balance" NUMBER(38,2) VISIBLE,
  "interest_rate" NUMBER(38,2) VISIBLE
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for TRANSACTIONS
-- ----------------------------
DROP TABLE "DEVUSER"."TRANSACTIONS";
CREATE TABLE "DEVUSER"."TRANSACTIONS" (
  "ACCOUNT_TYPE" NUMBER VISIBLE NOT NULL,
  "ACCOUNT_NUM" NUMBER VISIBLE NOT NULL,
  "TRANS_DATE" DATE VISIBLE NOT NULL,
  "TRANS_AMT" NUMBER(38,2) VISIBLE NOT NULL,
  "TRANS_TYPE" NUMBER VISIBLE NOT NULL,
  "trans_comments" VARCHAR2(255 BYTE) VISIBLE
)
TABLESPACE "devspace"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536
  NEXT 1048576
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table BRANCHES
-- ----------------------------
ALTER TABLE "DEVUSER"."BRANCHES" ADD CONSTRAINT "SYS_C007350" PRIMARY KEY ("BRANCH_NUM");

-- ----------------------------
-- Primary Key structure for table CHECKING_ACCOUNTS
-- ----------------------------
ALTER TABLE "DEVUSER"."CHECKING_ACCOUNTS" ADD CONSTRAINT "SYS_C007353" PRIMARY KEY ("ACCOUNT_NUM");

-- ----------------------------
-- Primary Key structure for table CUSTOMERS
-- ----------------------------
ALTER TABLE "DEVUSER"."CUSTOMERS" ADD CONSTRAINT "SYS_C007352" PRIMARY KEY ("CUSTOMER_NUM");

-- ----------------------------
-- Primary Key structure for table HAS_ACCOUNT
-- ----------------------------
ALTER TABLE "DEVUSER"."HAS_ACCOUNT" ADD CONSTRAINT "SYS_C007362" PRIMARY KEY ("CUSTOMER_NUM", "ACCOUNT_TYPE", "ACCOUNT_NUM");

-- ----------------------------
-- Primary Key structure for table LOAN_ACCOUNTS
-- ----------------------------
ALTER TABLE "DEVUSER"."LOAN_ACCOUNTS" ADD CONSTRAINT "SYS_C007359" PRIMARY KEY ("ACCOUNT_NUM");

-- ----------------------------
-- Primary Key structure for table SAVINGS_ACCOUNTS
-- ----------------------------
ALTER TABLE "DEVUSER"."SAVINGS_ACCOUNTS" ADD CONSTRAINT "SYS_C007356" PRIMARY KEY ("ACCOUNT_NUM");

-- ----------------------------
-- Primary Key structure for table TRANSACTIONS
-- ----------------------------
ALTER TABLE "DEVUSER"."TRANSACTIONS" ADD CONSTRAINT "SYS_C007364" PRIMARY KEY ("ACCOUNT_TYPE", "ACCOUNT_NUM", "TRANS_DATE", "TRANS_AMT", "TRANS_TYPE");

-- ----------------------------
-- Foreign Keys structure for table CHECKING_ACCOUNTS
-- ----------------------------
ALTER TABLE "DEVUSER"."CHECKING_ACCOUNTS" ADD CONSTRAINT "SYS_C007370" FOREIGN KEY ("branch_num") REFERENCES "DEVUSER"."BRANCHES" ("BRANCH_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table HAS_ACCOUNT
-- ----------------------------
ALTER TABLE "DEVUSER"."HAS_ACCOUNT" ADD CONSTRAINT "SYS_C007374" FOREIGN KEY ("CUSTOMER_NUM") REFERENCES "DEVUSER"."CUSTOMERS" ("CUSTOMER_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DEVUSER"."HAS_ACCOUNT" ADD CONSTRAINT "SYS_C007375" FOREIGN KEY ("ACCOUNT_NUM") REFERENCES "DEVUSER"."CHECKING_ACCOUNTS" ("ACCOUNT_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DEVUSER"."HAS_ACCOUNT" ADD CONSTRAINT "SYS_C007376" FOREIGN KEY ("ACCOUNT_NUM") REFERENCES "DEVUSER"."SAVINGS_ACCOUNTS" ("ACCOUNT_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "DEVUSER"."HAS_ACCOUNT" ADD CONSTRAINT "SYS_C007377" FOREIGN KEY ("ACCOUNT_NUM") REFERENCES "DEVUSER"."LOAN_ACCOUNTS" ("ACCOUNT_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table LOAN_ACCOUNTS
-- ----------------------------
ALTER TABLE "DEVUSER"."LOAN_ACCOUNTS" ADD CONSTRAINT "SYS_C007371" FOREIGN KEY ("branch_num") REFERENCES "DEVUSER"."BRANCHES" ("BRANCH_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table SAVINGS_ACCOUNTS
-- ----------------------------
ALTER TABLE "DEVUSER"."SAVINGS_ACCOUNTS" ADD CONSTRAINT "SYS_C007372" FOREIGN KEY ("branch_num") REFERENCES "DEVUSER"."BRANCHES" ("BRANCH_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
