CREATE TABLE EMPLOYEE
(
	EID VARCHAR(200) NOT NULL
		PRIMARY KEY ,
	NAME VARCHAR(200),
	COUNTRY VARCHAR(300),
	PROVINCE VARCHAR(300),
	CITY VARCHAR(300),
	POSTAL_CODE VARCHAR(300),
	STREET_ADDRESS LONG VARCHAR
);

INSERT INTO EMPLOYEE (EID, NAME, COUNTRY, PROVINCE, CITY, POSTAL_CODE, STREET_ADDRESS) VALUES ('eid1', 'ename1', 'Canada', 'Alberta', 'Athabasca', 'postalCode1', 'streetAddress1');
INSERT INTO EMPLOYEE (EID, NAME, COUNTRY, PROVINCE, CITY, POSTAL_CODE, STREET_ADDRESS) VALUES ('eid2', 'ename2', 'Canada', 'Alberta', 'Athabasca', 'postalCode1', 'streetAddress2');
INSERT INTO EMPLOYEE (EID, NAME, COUNTRY, PROVINCE, CITY, POSTAL_CODE, STREET_ADDRESS) VALUES ('eid3', 'ename3', 'Canada', 'Manitoba', 'Brandon', 'postalCode2', 'addr3');
INSERT INTO EMPLOYEE (EID, NAME, COUNTRY, PROVINCE, CITY, POSTAL_CODE, STREET_ADDRESS) VALUES ('5', '5', 'Canada', 'British Columbia', 'Abbotsford', '5', '5');
INSERT INTO EMPLOYEE (EID, NAME, COUNTRY, PROVINCE, CITY, POSTAL_CODE, STREET_ADDRESS) VALUES ('6', '5', 'Canada', 'British Columbia', 'Abbotsford', '5', '5');