# Generated by Django 3.0.3 on 2020-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_auto_20200217_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='_profile_followers_+', related_query_name='follower_profile_id', to='socialnetwork.Profile'),
        ),
    ]
