# Generated by Django 3.0.3 on 2020-02-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0004_auto_20200217_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='socialnetwork.Profile'),
        ),
    ]
