CC = gcc

smsh:
	$(CC) -o smsh1 smsh1.c splitline.c execute.c

part1:
	$(CC) -o smsh2 smsh2.c splitline.c execute.c part1.c

part2:
	$(CC) -o smsh3 smsh3.c splitline.c execute.c part1.c part2.c

part3:
	$(CC) -o smsh4 smsh4.c splitline.c execute.c part1.c part2.c part3.c